In [1]:
import numpy as np

In [26]:
wave1 =  np.array(range(20))

In [36]:
#前後5で移動平均
average_num=5
space_mean = np.convolve(wave1,np.ones(average_num)/average_num,mode = "valid")
print(len(space_mean))
space_mean

16


array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17.])

In [31]:
#縦になったときどのようになるかを見てみる
wave2 = np.array([wave1 for _ in range(3)])

In [32]:
wave2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [39]:
space_mean2 = np.array([np.convolve(wave,np.ones(average_num)/average_num,mode="valid") for wave in wave2 ])

In [41]:
wave3 =np.array([np.arange(0,10),np.arange(10,20),np.arange(20,30)])
wave3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [42]:
space_mean3 = np.array([np.convolve(wave,np.ones(average_num)/average_num,mode="valid") for wave in wave3 ])
space_mean3

array([[ 2.,  3.,  4.,  5.,  6.,  7.],
       [12., 13., 14., 15., 16., 17.],
       [22., 23., 24., 25., 26., 27.]])